--# 權限 `gettoeat`@`%`

CREATE USER 'gettoeat'@'%' IDENTIFIED BY PASSWORD '*5612ECF33F63FABE4CC02006090986E9111D4235';GRANT SELECT, INSERT, UPDATE, DELETE, LOCK TABLES ON `gettoeat`.* TO 'gettoeat'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;CREATE DATABASE IF NOT EXISTS `gettoeat`;

ALTER DATABASE `gettoeat` DEFAULT CHARSET=utf8 COLLATE utf8_unicode_ci;
